version: '3'
services:
    webdev:
        build: .
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
    db:
        image: mysql:5
        volumes:
            - db:/var/lib/mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: root
volumes:
    db: {}
